single : True
road_file : 'junction_path.txt'
rrt/max_failed_attemptes : 100000
rrt/t_max : 8
rrt/s_max : 100
rrt/t_goal : 5
rrt/v_goal : 12
rrt/dt : 0.1
rrt/max_acc : 5
rrt/max_vel : 15
rrt/kr : 100
rrt/ks : 5
rrt/kv : 5
rrt/lower_range_t : 1
rrt/lower_range_s : 10
rrt/upper_range_t : 1
rrt/upper_range_s : 10
rrt/upper_range_a: 0.1
rrt/lower_range_a: 0.1

rrt/k_risk : 10
rrt/danger_distance : 4.5
rrt/safe_distance : 100
rrt/car_width : 3
rrt/collision_distance : 4.5
rrt/safe_ttc : 5

single_test/single_test_case : 'turn_left_case'
single_test/collision_number : 1

emergency_stop_case/x0 : 520
emergency_stop_case/y0 : 497.5
emergency_stop_case/theta0 : 1.570
emergency_stop_case/v0 : 11
emergency_stop_case/a0 : 0
emergency_stop_case/obs1_x0 : 550
emergency_stop_case/obs1_y0 : 497.5
emergency_stop_case/obs1_theta0 : 1.570
emergency_stop_case/obs1_v0 : 0
emergency_stop_case/road_file : 'L1L3.txt'

crossing_case/x0 : 502.5
crossing_case/y0 : 480
crossing_case/theta0 : 0
crossing_case/v0 : 10
crossing_case/a0 : 0
crossing_case/obs1_x0 : 475
crossing_case/obs1_y0 : 497.5
crossing_case/obs1_theta0 : 1.570
crossing_case/obs1_v0 : 12
crossing_case/road_file : 'L7L6.txt'

turn_left_case/x0 : 502.5
turn_left_case/y0 : 480
turn_left_case/theta0 : 0
turn_left_case/v0 : 6
turn_left_case/a0 : 0
turn_left_case/obs1_x0 : 470
turn_left_case/obs1_y0 : 497.5
turn_left_case/obs1_theta0 : 1.570
turn_left_case/obs1_v0 : 8
turn_left_case/road_file : 'L7L2.txt'
turn_left_case/obs2_x0 : 500
turn_left_case/obs2_y0 : 502.5
turn_left_case/obs2_theta0 : -1.570
turn_left_case/obs2_v0 : 5

keep_lane_case/x0 : 540
keep_lane_case/y0 : 497.5
keep_lane_case/theta0 : 1.570
keep_lane_case/v0 : 10
keep_lane_case/a0 : 1
keep_lane_case/obs1_x0 : 520
keep_lane_case/obs1_y0 : 497.5
keep_lane_case/obs1_theta0 : 1.570
keep_lane_case/obs1_v0 : 11
keep_lane_case/obs2_x0 : 570
keep_lane_case/obs2_y0 : 497.5
keep_lane_case/obs2_theta0 : 1.570
keep_lane_case/obs2_v0 : 12
keep_lane_case/road_file : 'L1L3.txt'

junction_case/x0 : -50
junction_case/y0 : -2.5
junction_case/theta0 : 1.570
junction_case/v0 : 20
junction_case/a0 : 0
